// packages/vue/src/components/pspicture.vue
<template>
  <div :style="`width: ${size.width}px; height: ${size.height}px;`" class="pspicture">
    <svg ref="svg" :width="`${size.width}px`" :height="`${size.height}px`" />
  </div>
</template>

<script>
import { psgraph } from '@latex2js/pstricks';
import * as d3 from 'd3';

export default {
  props: ['lines', 'plot', 'settings', 'env'],
  computed: {
    size() {
      return psgraph.getSize.call(this);
    },
  },
  mounted() {
    var svg = d3.select(this.$refs.svg);
    psgraph.pspicture.call(this, svg);
  },
};
</script>

// packages/react/src/components/pspicture.tsx
import { psgraph } from '@latex2js/pstricks';
import * as d3 from 'd3';
import { useRef, useEffect } from 'react';
import Slider from './slider';

interface PspictureProps {
  env: {
    sliders?: Array<{
      latex: string;
      scalar: number;
      variable: string;
      value: string;
      min: number;
      max: number;
    }>;
    variables?: { [key: string]: number };
  };
  plot: { [key: string]: any };
  [key: string]: any;
}

export default (props: PspictureProps) => {
  const svgRef = useRef<SVGSVGElement>(null);
  const divRef = useRef<HTMLDivElement>(null);
  const size = psgraph.getSize.call(props);
  const width = `${size.width}px`;
  const height = `${size.height}px`;

  useEffect(() => {
    if (svgRef.current && divRef.current) {
      const d3svg = d3.select(svgRef.current);
      const obj = { ...props };
      obj.$el = divRef.current;
      psgraph.pspicture.call(obj, d3svg);
    }
  }, [props]);

  return (
    <div
      className="pspicture"
      style={{ width: width, height: height }}
      ref={divRef}
    >
      <svg width={size.width} height={size.height} ref={svgRef} />
      {props.env.sliders &&
        props.env.sliders.map((slider: any, index: number) => {
          return (
            <Slider
              key={index}
              slider={slider}
              env={props.env}
              svgRef={svgRef}
              plot={props.plot}
            />
          );
        })}
    </div>
  );
};
